export type SingleTopicKey =
  | 'nano_banana_posters'
  | 'viral_hook_secrets'
  | 'higgsfield_video_directing'
  | 'jacquemus_street_art'
  | 'automated_dm_sales'
  | 'spring_physics_video'
  | 'founder_origin_reframe'
  | 'brand_transformation_story'
  | 'visual_directing_cinema_story'
  | 'ciel_invisible_craft_story'
  | 'transformation_framework_story'
  | 'ciel_uncanny_luxury_story'
  | 'auteur_cultural_moat_story';

export interface CarouselSlideCopy {
  slideIndex: number;
  slideType: string;
  header: string;
  subhead?: string;
  bodyBullets?: string[];
  keyCallout?: string;
  badgeText?: string;
  highlightWords?: string[];
  stickerTags?: { text: string; color: 'pink' | 'green' | 'blue' | 'yellow' }[];
  icons?: string[]; // e.g. ['🍒', '⚡', '🪩', '💸', '🖱️']
  swissHudMetadata?: string;
  swipePrompt?: string;
  cardIndexText: string;
}

export interface CarouselCopyPackage {
  topicKey: SingleTopicKey;
  topicTitle: string;
  triggerWord: string;
  hookHeadline: string;
  slides: CarouselSlideCopy[];
  instagramCaption: string;
  hashtags: string[];
}

export const SINGLE_TOPIC_CAROUSEL_BLUEPRINTS: Record<
  SingleTopicKey,
  {
    topicTitle: string;
    triggerWord: string;
    captionHook: string;
    slides: Omit<CarouselSlideCopy, 'slideIndex' | 'cardIndexText'>[];
  }
> = {
  nano_banana_posters: {
    topicTitle: 'How to Make $5,000 Luxury Brand Posters in Nano Banana (In 3 Minutes)',
    triggerWord: 'POSTER',
    captionHook: 'How to make $5K luxury brand posters in Nano Banana in under 3 minutes.',
    slides: [
      {
        slideType: 'hook',
        header: 'how to make $5k luxury brand posters in 3 minutes.',
        subhead: 'You do not need Photoshop or complex 3D software. Just this simple reference formula.',
        badgeText: 'NANO BANANA RECIPE',
        highlightWords: ['luxury', 'posters', '3 minutes'],
        stickerTags: [
          { text: 'Simple Strategy', color: 'green' },
          { text: 'Nano Banana 2', color: 'pink' },
        ],
        icons: ['🍒', '⚡', '🪩', '🖱️'],
        swissHudMetadata: '01 // POSTER DESIGN // SPEC 2026',
        swipePrompt: 'SWIPE FOR THE PROMPT →',
      },
      {
        slideType: 'problem',
        header: 'why 90% of ai posters look cheap and messy.',
        subhead: 'Typing random words gives you chaotic layouts, blurry fonts, and plastic lighting.',
        bodyBullets: [
          'Mistake 1: Starting with a blank prompt instead of a reference layout',
          'Mistake 2: Asking for too many elements at once (visual clutter)',
          'Mistake 3: Zero grid structure or typographic hierarchy',
        ],
        keyCallout: 'RULE: Great design is not about more prompt words. It is about strict layout rules.',
        badgeText: 'THE BIG MISTAKE',
        highlightWords: ['cheap', 'messy'],
        stickerTags: [{ text: 'Why Ads Fail', color: 'pink' }],
        icons: ['💸'],
        swissHudMetadata: '02 // THE PROBLEM // VISUAL CLUTTER',
        swipePrompt: 'STEP 1: THE GRID →',
      },
      {
        slideType: 'step1',
        header: 'step 1: pick a grid reference layout.',
        subhead: 'Never start from scratch. Upload a graphic poster you love to guide the structure.',
        bodyBullets: [
          'Choose a poster with bold stacked typography and clean grid lines',
          'Let Nano Banana analyze the spacing, fonts, and color contrast',
          'Keep the background minimal (off-white graph grid or deep black)',
        ],
        keyCallout: 'PRO TIP: Reference images act as the blueprint for your typography.',
        badgeText: 'STEP 01: THE GRID',
        highlightWords: ['grid reference', 'layout'],
        stickerTags: [{ text: 'Layout Blueprint', color: 'blue' }],
        icons: ['⚡', '🖱️'],
        swissHudMetadata: '03 // STEP 01 // GRID LAYOUT',
        swipePrompt: 'STEP 2: THE PROMPT →',
      },
      {
        slideType: 'step2',
        header: 'step 2: the exact copy-paste prompt formula.',
        subhead: 'Paste this exact prompt structure into Nano Banana:',
        bodyBullets: [
          '1. "Use this image as reference for composition and typographic layout."',
          '2. "Swap main text to: [YOUR TITLE]. Archivo Black + Playfair Serif."',
          '3. "Lighting: 50mm clean prime portrait, soft raking key light, 35mm film grain."',
        ],
        keyCallout: 'PROMPT: "Use reference style, add 50mm macro lighting, razor-sharp typography, 4:5 vertical poster."',
        badgeText: 'STEP 02: THE PROMPT',
        highlightWords: ['copy-paste', 'prompt formula'],
        stickerTags: [{ text: 'Free Code', color: 'green' }],
        icons: ['🍒', '💸'],
        swissHudMetadata: '04 // STEP 02 // PROMPT CODE',
        swipePrompt: 'STEP 3: STICKERS →',
      },
      {
        slideType: 'step3',
        header: 'step 3: add retro stickers & pastel highlights.',
        subhead: 'This is what gives the poster that high-end editorial agency aesthetic.',
        bodyBullets: [
          'Add a soft pastel pink or lime highlighter strip behind the main keyword',
          'Layer small speech bubbles with mini descriptive notes',
          'Drop 3D micro icons (cherries, lightning, retro mouse cursors) near the letters',
        ],
        keyCallout: 'SECRET: Floating micro-stickers turn flat text into an interactive artwork.',
        badgeText: 'STEP 03: MICRO ACCENTS',
        highlightWords: ['retro stickers', 'highlights'],
        stickerTags: [
          { text: 'Collage Style', color: 'pink' },
          { text: 'Interactive', color: 'yellow' },
        ],
        icons: ['🪩', '⚡', '🍒'],
        swissHudMetadata: '05 // STEP 03 // STICKERS & ACCENTS',
        swipePrompt: 'THE CHEAT SHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: 'the saveable poster cheat sheet.',
        subhead: 'Save this slide for your next product poster creation:',
        bodyBullets: [
          '🎯 Canvas Size: 1080 x 1350 (4:5 vertical ratio)',
          '🎨 Colors: Off-white graph paper (#F9F9F7) + Black text + Neon lime/pink',
          '🔤 Typography: Extra Bold Sans Serif + Italic Display Serif (stacked tightly)',
          '✨ Finish: Raking side key light, lifted shadows, 35mm film grain',
        ],
        keyCallout: '💾 SAVE THIS POST: Keep these 4 rules ready whenever you open Nano Banana!',
        badgeText: 'SAVEABLE CHEAT SHEET',
        highlightWords: ['cheat sheet', 'save this'],
        stickerTags: [{ text: 'Pocket Guide', color: 'green' }],
        icons: ['💾', '⚡'],
        swissHudMetadata: '06 // CHEAT SHEET // SAVE FOR LATER',
        swipePrompt: 'THE WINNING WORKFLOW →',
      },
      {
        slideType: 'summary',
        header: 'the 3-minute poster workflow.',
        subhead: 'How to make 10 high-converting posters every single day:',
        bodyBullets: [
          '1. Save 5 aesthetic reference posters from Pinterest / Instagram',
          '2. Feed into Nano Banana with our 3-line copy formula',
          '3. Export high-res and pair with an automated DM keyword',
        ],
        keyCallout: '✈️ SHARE WITH A CREATOR: Help a friend level up their graphic design!',
        badgeText: 'THE COMPLETE WORKFLOW',
        highlightWords: ['3-minute', 'workflow'],
        stickerTags: [{ text: 'Scale to 10x', color: 'blue' }],
        icons: ['🚀', '💸'],
        swissHudMetadata: '07 // WORKFLOW // DAILY ENGINE',
        swipePrompt: 'CLAIM THE FREE PROMPT PACK →',
      },
      {
        slideType: 'cta',
        header: 'want the free poster prompt pack & figma templates?',
        subhead: 'All raw assets, prompt files, and breakdowns are posted in our private Telegram group.',
        bodyBullets: [
          '💬 Drop "POSTER" below for the instant Telegram invite link',
          '📲 All prompt templates & editable Figma files are pinned in our Telegram group',
          '🚀 Follow @junnbuilds / project\\ciel for daily creator breakdowns',
        ],
        keyCallout: '⚡ Instant Telegram Access: Drop "POSTER" below or check the link in bio!',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['telegram group', 'free prompt pack'],
        stickerTags: [{ text: 'Telegram Group', color: 'blue' }],
        icons: ['📲', '⚡', '🎁'],
        swissHudMetadata: '08 // TELEGRAM VIP // DROP "POSTER" BELOW',
        swipePrompt: 'DROP "POSTER" FOR TELEGRAM LINK ↓',
      },
    ],
  },

  viral_hook_secrets: {
    topicTitle: 'The 3-Second Hook Secret That Makes Millions Stop Scrolling',
    triggerWord: 'HOOKS',
    captionHook: 'The 3-second hook secret that makes millions stop scrolling.',
    slides: [
      {
        slideType: 'hook',
        header: 'the 3-second hook secret that stops the scroll.',
        subhead: 'How top creators write opening lines that hook viewers, hold them for 15 seconds, and go viral.',
        badgeText: 'VIRAL HOOK FORMULA',
        highlightWords: ['3-second', 'hook secret', 'stop the scroll'],
        stickerTags: [
          { text: 'Retention Science', color: 'green' },
          { text: '1.5s Gate', color: 'pink' },
        ],
        icons: ['⚡', '🍒', '🪩', '🖱️'],
        swissHudMetadata: '01 // VIRAL HOOKS // RETENTION SPEC',
        swipePrompt: 'WHY MOST DIE IN 2S →',
      },
      {
        slideType: 'problem',
        header: 'why 90% of videos die in the first 2 seconds.',
        subhead: 'Starting with boring greetings ("Hey guys") or channel logos kills distribution instantly.',
        bodyBullets: [
          'The algorithm decides in 1.5 to 3 seconds whether to push your video',
          'Throat-clearing and slow intros cause 80% immediate drop-off',
          'Viewers want the prize immediately, not your autobiography',
        ],
        keyCallout: 'RULE: Never introduce yourself. Start right inside the middle of the transformation.',
        badgeText: 'THE RETENTION TRAP',
        highlightWords: ['die in 2 seconds', 'drop-off'],
        stickerTags: [{ text: 'Algorithm Gate', color: 'pink' }],
        icons: ['💸'],
        swissHudMetadata: '02 // RETENTION TRAP // WHY IT DIES',
        swipePrompt: 'LAYER 1: VISUAL SHOCK →',
      },
      {
        slideType: 'step1',
        header: 'layer 1: the silent visual shock.',
        subhead: 'Your video must stop thumbs on mute before the viewer hears a single word.',
        bodyBullets: [
          'Show an impossible, oversized, or high-contrast physical object',
          'Use extreme close-up macro texture (water droplets, raking light, liquid splash)',
          'When the first frame looks visually shocking, the thumb freezes',
        ],
        keyCallout: 'VISUAL RULE: The first frame must make sense and look stunning even on mute.',
        badgeText: 'LAYER 01: VISUAL SHOCK',
        highlightWords: ['silent', 'visual shock'],
        stickerTags: [{ text: 'Works on Mute', color: 'blue' }],
        icons: ['🪩', '⚡'],
        swissHudMetadata: '03 // LAYER 01 // VISUAL SHOCK',
        swipePrompt: 'LAYER 2: SPOKEN INTRIGUE →',
      },
      {
        slideType: 'step2',
        header: 'layer 2: the spoken intrigue (under 2s).',
        subhead: 'Lead with the shocking prize or counter-intuitive truth.',
        bodyBullets: [
          'Bad: "Today I want to show you how to edit videos faster."',
          'Good: "I spent $10,000 on video gear so you can copy the $0 formula."',
          'Open a curiosity gap that the viewer MUST watch 15s to resolve',
        ],
        keyCallout: 'VERBAL RULE: Lead with the prize, withhold the answer until slide 3.',
        badgeText: 'LAYER 02: SPOKEN INTRIGUE',
        highlightWords: ['spoken intrigue', 'curiosity gap'],
        stickerTags: [{ text: 'Curiosity Loop', color: 'green' }],
        icons: ['🍒', '💸'],
        swissHudMetadata: '04 // LAYER 02 // SPOKEN INTRIGUE',
        swipePrompt: 'LAYER 3: ON-SCREEN PUNCH →',
      },
      {
        slideType: 'step3',
        header: 'layer 3: the 4-word on-screen punchline.',
        subhead: 'Do not repeat the spoken words. Sharpen the message into 4 big bold words.',
        bodyBullets: [
          'Spoken: "Your expensive camera is why your videos look worse."',
          'On-screen text: "$3,000 vs $0 Truth."',
          'High contrast typography with a neon highlighter strip behind the keyword',
        ],
        keyCallout: 'TEXT RULE: 3 to 7 high-impact words that punch the message into their eyes.',
        badgeText: 'LAYER 03: ON-SCREEN PUNCH',
        highlightWords: ['4-word', 'punchline'],
        stickerTags: [{ text: 'High Contrast', color: 'yellow' }],
        icons: ['⚡', '🖱️'],
        swissHudMetadata: '05 // LAYER 03 // ON-SCREEN TEXT',
        swipePrompt: '5 TEMPLATES CHEAT SHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: '5 copy-paste viral hook templates.',
        subhead: 'Save these 5 proven hook archetypes for your next video shoot:',
        bodyBullets: [
          '1. The Cost Confession: "I spent $X so you can skip to $0."',
          '2. The Contrarian: "Why [common habit] is ruining your [desired result]."',
          '3. The Withheld Reveal: "I found the 1 tool that actually works (not what you think)."',
          '4. The Juxtaposition: "Why putting [luxury item] in [gritty street] went viral."',
          '5. The 3-Minute Fix: "How to fix [big headache] in 1 click."',
        ],
        keyCallout: '💾 SAVE THIS POST: Use these 5 templates whenever you write your next hook!',
        badgeText: 'SAVEABLE CHEAT SHEET',
        highlightWords: ['viral hook templates', 'save this'],
        stickerTags: [{ text: '5 Plug-and-Play', color: 'green' }],
        icons: ['💾', '🍒'],
        swissHudMetadata: '06 // CHEAT SHEET // 5 HOOK TEMPLATES',
        swipePrompt: 'THE 15S RETENTION CURVE →',
      },
      {
        slideType: 'summary',
        header: 'the 15-second viral retention curve.',
        subhead: 'How to turn a 3-second hook into a completed watch and comment:',
        bodyBullets: [
          '0-3s: Hook (Visual shock + Spoken intrigue + 4-word text)',
          '4-8s: Tension (Explain why the standard way fails)',
          '9-13s: Reward (Deliver the exact actionable formula)',
          '14-15s: CTA (Comment keyword for the free complete PDF)',
        ],
        keyCallout: '✈️ SHARE WITH A CREATOR: Help someone stop losing viewers in second 2!',
        badgeText: 'RETENTION CURVE',
        highlightWords: ['retention curve', '15-second'],
        stickerTags: [{ text: 'Algorithm Proof', color: 'blue' }],
        icons: ['🚀', '⚡'],
        swissHudMetadata: '07 // RETENTION // 15S SYSTEM',
        swipePrompt: 'CLAIM THE FREE 25 HOOK PACK →',
      },
      {
        slideType: 'cta',
        header: 'want the free 25 viral hook templates pack?',
        subhead: 'All raw hook templates, swipe files, and breakdowns are posted in our private Telegram group.',
        bodyBullets: [
          '💬 Drop "HOOKS" below for the instant Telegram invite link',
          '📲 All 25 hook scripts & retention templates are pinned in our Telegram group',
          '🚀 Follow @junnbuilds / project\\ciel for daily visual directing secrets',
        ],
        keyCallout: '⚡ Instant Telegram Access: Drop "HOOKS" below or check the link in bio!',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['telegram group', 'free hook templates'],
        stickerTags: [{ text: 'Telegram Group', color: 'blue' }],
        icons: ['📲', '⚡', '🎁'],
        swissHudMetadata: '08 // TELEGRAM VIP // DROP "HOOKS" BELOW',
        swipePrompt: 'DROP "HOOKS" FOR TELEGRAM LINK ↓',
      },
    ],
  },

  higgsfield_video_directing: {
    topicTitle: 'How to Direct 4K Product Videos with Real Fluid Physics in Higgsfield',
    triggerWord: 'CINEMA',
    captionHook: 'How to direct 4K product videos with real fluid physics in Higgsfield.',
    slides: [
      {
        slideType: 'hook',
        header: 'how to direct 4k product videos with real fluid physics.',
        subhead: 'Stop making stiff robot AI videos. Here is how to add weight, bounce, and cinematic motion.',
        badgeText: 'HIGGSFIELD CINEMA SPEC',
        highlightWords: ['4k product videos', 'fluid physics'],
        stickerTags: [
          { text: 'Soul Cinema', color: 'green' },
          { text: 'Real Physics', color: 'pink' },
        ],
        icons: ['🍒', '⚡', '🪩', '🖱️'],
        swissHudMetadata: '01 // HIGGSFIELD // CAMERA DIRECTING',
        swipePrompt: 'SWIPE FOR CAMERA MOVES →',
      },
      {
        slideType: 'problem',
        header: 'why straight-line robot motion kills buyer trust.',
        subhead: 'When an object glides at constant speed with zero gravity, your brain knows it is fake.',
        bodyBullets: [
          'Linear speed feels like a cheap 2010 video game',
          'Real objects accelerate, decelerate, and have momentum',
          'Without physical weight and sound impact, viewers swipe away',
        ],
        keyCallout: 'RULE: Real physics creates organic trust and makes products feel expensive.',
        badgeText: 'THE ROBOT TRAP',
        highlightWords: ['robot motion', 'fake physics'],
        stickerTags: [{ text: 'Physics Trap', color: 'pink' }],
        icons: ['💸'],
        swissHudMetadata: '02 // THE PROBLEM // ZERO WEIGHT',
        swipePrompt: 'SECRET 1: 50MM OPTICAL PRIME →',
      },
      {
        slideType: 'step1',
        header: 'secret 1: 50mm optical prime & raking key light.',
        subhead: 'The lens you pick in your prompt changes everything.',
        bodyBullets: [
          'Use 50mm or 85mm optical prime lenses for flattering portrait compression',
          'Position a strong raking side key light to reveal micro-textures and glass cuts',
          'Keep shadows open and lifted with subtle 35mm film grain',
        ],
        keyCallout: 'PROMPT TAG: "50mm optical prime, raking side key light, soft highlight roll-off."',
        badgeText: 'SECRET 01: CINEMA OPTICS',
        highlightWords: ['50mm optical prime', 'raking light'],
        stickerTags: [{ text: 'Cinema Glass', color: 'blue' }],
        icons: ['🪩', '⚡'],
        swissHudMetadata: '03 // SECRET 01 // LENS & LIGHT',
        swipePrompt: 'SECRET 2: SLOW DOLLY IN →',
      },
      {
        slideType: 'step2',
        header: 'secret 2: slow macro dolly in & 1/10,000s shutter.',
        subhead: 'Bring physical details to life with micro slow-motion splashes.',
        bodyBullets: [
          'Move the camera slowly inward to create depth and anticipation',
          'Freeze micro liquid droplets and mist with high shutter speed math',
          'Avoid crazy spinning 360 orbits — keep camera motion intentional',
        ],
        keyCallout: 'PROMPT TAG: "Slow cinematic dolly in on hero object, 1/10,000s shutter liquid splash."',
        badgeText: 'SECRET 02: CAMERA MOVE',
        highlightWords: ['macro dolly in', 'shutter speed'],
        stickerTags: [{ text: 'Liquid Viscosity', color: 'green' }],
        icons: ['🍒', '💸'],
        swissHudMetadata: '04 // SECRET 02 // DOLLY & SHUTTER',
        swipePrompt: 'SECRET 3: SPRING PHYSICS →',
      },
      {
        slideType: 'step3',
        header: 'secret 3: spring physics & sub-bass audio impacts.',
        subhead: 'Sound is 50% of how real an AI video feels.',
        bodyBullets: [
          'Pair the visual drop with a deep tactile sub-bass impact sound',
          'Add high-frequency texture sounds (glass clinking, mist spraying, cloth rustle)',
          'When sound and spring physics sync, the screen feels tangible',
        ],
        keyCallout: 'AUDIO RULE: Deep tactile bass + crisp micro-sound effects = physical reality.',
        badgeText: 'SECRET 03: SOUND DESIGN',
        highlightWords: ['spring physics', 'sub-bass audio'],
        stickerTags: [{ text: 'Sound Design', color: 'yellow' }],
        icons: ['⚡', '🖱️'],
        swissHudMetadata: '05 // SECRET 03 // AUDIO PHYSICS',
        swipePrompt: 'THE HIGGSFIELD CHEAT SHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: 'the copy-paste higgsfield video prompt.',
        subhead: 'Save this exact video generation code for Soul Cinema / Seedance:',
        bodyBullets: [
          '🎥 Framing: "Medium shot, cinematic slow dolly in on hero object, 50mm FOV"',
          '💧 Physics: "Natural gravity and inertia, macro liquid viscosity splash at 1/10,000s shutter"',
          '🎞️ Finish: "Volumetric raking light, deep open shadows, fine 35mm motion-picture grain"',
          '🚫 Negative: "No CGI sheen, no plastic skin, no video game artifacts, real optical capture"',
        ],
        keyCallout: '💾 SAVE THIS POST: Copy-paste this exact prompt into Higgsfield!',
        badgeText: 'SAVEABLE CHEAT SHEET',
        highlightWords: ['higgsfield prompt', 'copy-paste code'],
        stickerTags: [{ text: 'Video Code', color: 'green' }],
        icons: ['💾', '🍒'],
        swissHudMetadata: '06 // CHEAT SHEET // HIGGSFIELD CODE',
        swipePrompt: 'THE 3-STEP PIPELINE →',
      },
      {
        slideType: 'summary',
        header: 'the 3-step high-converting video pipeline.',
        subhead: 'From still poster to 4K cinematic commercial:',
        bodyBullets: [
          '1. Nano Banana: Generate high-res 4:5 visual poster with clean lighting',
          '2. Higgsfield: Animate the hero object with our 50mm camera code',
          '3. OpenReply DM Bot: Deliver product link the second someone comments',
        ],
        keyCallout: '✈️ SHARE WITH A VIDEO CREATOR: Level up someone’s AI video quality today!',
        badgeText: 'THE 3-STEP PIPELINE',
        highlightWords: ['video pipeline', 'high-converting'],
        stickerTags: [{ text: 'Full Workflow', color: 'blue' }],
        icons: ['🚀', '⚡'],
        swissHudMetadata: '07 // PIPELINE // AUTONOMOUS ENGINE',
        swipePrompt: 'CLAIM THE FREE CINEMA PACK →',
      },
      {
        slideType: 'cta',
        header: 'want the free 4k higgsfield video prompt pack?',
        subhead: 'Drop a 1-word comment below and I will instantly DM you all camera codes & settings!',
        bodyBullets: [
          '💬 Comment "CINEMA" on this post right now',
          '📥 Automated DM sends the complete 4K camera codes + lighting cheat sheet in 2s',
          '🚀 Follow @junnbuilds / project\\ciel for daily AI directing secrets',
        ],
        keyCallout: '⚡ Instant free delivery: Drop "CINEMA" below to get the download link.',
        badgeText: 'FREE PRIZE',
        highlightWords: ['4k prompt pack', 'camera codes'],
        stickerTags: [{ text: 'Instant DM', color: 'pink' }],
        icons: ['🎁', '⚡', '🖱️'],
        swissHudMetadata: '08 // FREE PRIZE // DROP "CINEMA" BELOW',
        swipePrompt: 'COMMENT "CINEMA" NOW ↓',
      },
    ],
  },

  jacquemus_street_art: {
    topicTitle: 'Scale Disruption & Surreal Street Art: The Jacquemus Strategy',
    triggerWord: 'SCALE',
    captionHook: 'How Jacquemus gets 50 million views by breaking physical scale in streets.',
    slides: [
      {
        slideType: 'hook',
        header: 'the jacquemus secret: scale disruption in public streets.',
        subhead: 'How turning giant luxury handbags into public streetcars generated 50M views with zero ad spend.',
        badgeText: 'SURREAL STREET ART',
        highlightWords: ['scale disruption', 'jacquemus secret'],
        stickerTags: [
          { text: '50M Views', color: 'green' },
          { text: 'Zero Ad Spend', color: 'pink' },
        ],
        icons: ['🍒', '⚡', '🪩', '🖱️'],
        swissHudMetadata: '01 // JACQUEMUS // SCALE DISRUPTION',
        swipePrompt: 'WHY CLEAN ADS DIE →',
      },
      {
        slideType: 'problem',
        header: 'why clean studio product renders are invisible.',
        subhead: 'When everything is clean, perfect, and isolated on a white screen, your brain ignores it.',
        bodyBullets: [
          'Studio renders look like ordinary catalog advertisements',
          'Our brains are wired to notice things that look out of place in the real world',
          'Putting luxury inside brutalist concrete streets creates instant thumb-stopping contrast',
        ],
        keyCallout: 'RULE: Contrast creates curiosity, and curiosity creates millions of organic shares.',
        badgeText: 'THE INVISIBILITY TRAP',
        highlightWords: ['studio renders', 'invisible'],
        stickerTags: [{ text: 'Pattern Interrupt', color: 'pink' }],
        icons: ['💸'],
        swissHudMetadata: '02 // THE PROBLEM // STUDIO ADS',
        swipePrompt: 'STEP 1: THE 10X SCALE RULE →',
      },
      {
        slideType: 'step1',
        header: 'step 1: the 10x impossible scale rule.',
        subhead: 'Take one small physical luxury item and scale it up to the size of a building or bus.',
        bodyBullets: [
          'A 5-inch lipstick turned into a 20-foot city transit bus',
          'A luxury handbag floating down the Seine river like a giant boat',
          'Keep the material, leather grain, and stitching 100% physically authentic',
        ],
        keyCallout: 'SCALE RULE: Extreme surreal scale + 100% real physical texture = viral magic.',
        badgeText: 'STEP 01: 10X SCALE',
        highlightWords: ['10x scale', 'impossible'],
        stickerTags: [{ text: 'Impossible Scale', color: 'blue' }],
        icons: ['🪩', '⚡'],
        swissHudMetadata: '03 // STEP 01 // 10X SCALE',
        swipePrompt: 'STEP 2: URBAN CONTRAST →',
      },
      {
        slideType: 'step2',
        header: 'step 2: raw brutalist urban environments.',
        subhead: 'Anchor the impossible object inside mundane, everyday physical architecture.',
        bodyBullets: [
          'Paris cobblestone streets, London rainy crosswalks, brutalist concrete tunnels',
          'Include real background elements: pedestrians walking, streetlights, asphalt reflections',
          'The contrast between gritty streets and immaculate luxury creates high prestige',
        ],
        keyCallout: 'ENVIRONMENT RULE: The more ordinary the street, the more shocking the luxury object.',
        badgeText: 'STEP 02: URBAN CONTRAST',
        highlightWords: ['raw brutalist', 'urban contrast'],
        stickerTags: [{ text: 'Gritty vs Luxury', color: 'green' }],
        icons: ['🍒', '💸'],
        swissHudMetadata: '04 // STEP 02 // STREET CONTRAST',
        swipePrompt: 'STEP 3: CAMERA CONFIRMATION →',
      },
      {
        slideType: 'step3',
        header: 'step 3: handheld camera & bystander angle.',
        subhead: 'Shoot the scene from a realistic human perspective, not a floating drone.',
        bodyBullets: [
          'Eye-level handheld camera with subtle natural shake',
          'Casual street bystander angle makes the scene feel like a real iPhone recording',
          'When viewers think "Is that real?!", they comment, share, and tag their friends',
        ],
        keyCallout: 'PERSPECTIVE RULE: Bystander angle turns a CGI render into a trending viral moment.',
        badgeText: 'STEP 03: EYE-LEVEL ANGLE',
        highlightWords: ['handheld camera', 'bystander angle'],
        stickerTags: [{ text: 'Real Human POV', color: 'yellow' }],
        icons: ['⚡', '🖱️'],
        swissHudMetadata: '05 // STEP 03 // CAMERA ANGLE',
        swipePrompt: 'THE SCALE CHEAT SHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: 'the jacquemus prompt cheat sheet.',
        subhead: 'Save this exact scale-disruption prompt formula for Nano Banana & Higgsfield:',
        bodyBullets: [
          '🏢 Object: "Giant 20-foot monolithic luxury perfume bottle driving down rainy Paris street"',
          '🌧️ Lighting: "Overcast moody sky, wet asphalt reflections, raking golden street lamps"',
          '📱 Camera: "Eye-level 50mm handheld bystander perspective, natural camera shake"',
          '🧪 Finish: "Authentic glass refraction, real rainwater physics, 35mm film grain"',
        ],
        keyCallout: '💾 SAVE THIS POST: Use this formula whenever you launch a physical product campaign!',
        badgeText: 'SAVEABLE CHEAT SHEET',
        highlightWords: ['jacquemus prompt', 'cheat sheet'],
        stickerTags: [{ text: 'Scale Formula', color: 'green' }],
        icons: ['💾', '🍒'],
        swissHudMetadata: '06 // CHEAT SHEET // SCALE PROMPT',
        swipePrompt: 'THE VIRAL ROI SYSTEM →',
      },
      {
        slideType: 'summary',
        header: 'the 3-step viral disruption blueprint.',
        subhead: 'How to turn viral street attention into tracked brand sales:',
        bodyBullets: [
          '1. Scale Disruption Video: 15s surreal street video stops the algorithm',
          '2. Viral Comment Loop: Viewers debate "Is this real?" in the comments',
          '3. Automated DM Playbook: Sends private shop link to everyone who comments',
        ],
        keyCallout: '✈️ SHARE WITH A BRAND FOUNDER: Show them how to get millions of views with zero ad spend!',
        badgeText: 'VIRAL BLUEPRINT',
        highlightWords: ['viral disruption', 'brand sales'],
        stickerTags: [{ text: 'Zero Ad Spend', color: 'blue' }],
        icons: ['🚀', '⚡'],
        swissHudMetadata: '07 // BLUEPRINT // ORGANIC REACH',
        swipePrompt: 'CLAIM THE FREE SCALE PACK →',
      },
      {
        slideType: 'cta',
        header: 'want the full jacquemus scale prompt pack?',
        subhead: 'Drop a 1-word comment below and I will instantly DM you all 10 scale prompt formulas!',
        bodyBullets: [
          '💬 Comment "SCALE" on this post right now',
          '📥 Automated DM sends all 10 urban scale prompt codes + lighting setups in 2s',
          '🚀 Follow @junnbuilds / project\\ciel for daily luxury directing breakdowns',
        ],
        keyCallout: '⚡ Instant free delivery: Drop "SCALE" below to get the download link.',
        badgeText: 'FREE PRIZE',
        highlightWords: ['scale prompt pack', '10 formulas'],
        stickerTags: [{ text: 'Instant DM', color: 'pink' }],
        icons: ['🎁', '⚡', '🖱️'],
        swissHudMetadata: '08 // FREE PRIZE // DROP "SCALE" BELOW',
        swipePrompt: 'COMMENT "SCALE" NOW ↓',
      },
    ],
  },

  automated_dm_sales: {
    topicTitle: 'How to Turn Instagram Comments into Automatic Sales 24/7',
    triggerWord: 'SALES',
    captionHook: 'How we turn 1 simple comment into automatic sales while we sleep.',
    slides: [
      {
        slideType: 'hook',
        header: 'how to turn 1 simple comment into sales while you sleep.',
        subhead: 'You do not need to beg people to click the link in bio. Set up this automated DM robot in 2 minutes.',
        badgeText: 'COMMERCE FUNNEL',
        highlightWords: ['sales while you sleep', 'automated dm'],
        stickerTags: [
          { text: 'Autopilot Sales', color: 'green' },
          { text: '2-Min Setup', color: 'pink' },
        ],
        icons: ['🍒', '⚡', '🪩', '🖱️'],
        swissHudMetadata: '01 // COMMERCE // AUTOMATED FUNNEL',
        swipePrompt: 'THE BIO LINK TRAP →',
      },
      {
        slideType: 'problem',
        header: 'why "link in bio" loses 90% of your buyers.',
        subhead: 'Forcing people to leave the feed, open your profile, and find a tiny link kills conversion.',
        bodyBullets: [
          'Every extra click cuts conversion rate in half',
          'People are lazy and do not want to leave the Instagram feed',
          'When they leave the post to find your bio, they get distracted and forget',
        ],
        keyCallout: 'RULE: Never ask them to go to your bio. Deliver the link straight to their private DMs.',
        badgeText: 'THE BIO LINK TRAP',
        highlightWords: ['loses 90%', 'kills conversion'],
        stickerTags: [{ text: 'Friction Point', color: 'pink' }],
        icons: ['💸'],
        swissHudMetadata: '02 // THE PROBLEM // BIO LINK',
        swipePrompt: 'STEP 1: THE 1-WORD TRIGGER →',
      },
      {
        slideType: 'step1',
        header: 'step 1: the low-friction 1-word trigger keyword.',
        subhead: 'Make it effortlessly easy for the viewer to claim the free value.',
        bodyBullets: [
          'Pick a simple 1-word keyword (e.g. "CIEL", "POSTER", "SCALE")',
          'Tell them exactly what happens: "Comment POSTER and I will DM you the prompt pack"',
          'Single words require 0 typing friction and trigger high comment velocity',
        ],
        keyCallout: 'KEYWORD RULE: 1 simple word = 10x more comments and higher algorithmic push.',
        badgeText: 'STEP 01: 1-WORD TRIGGER',
        highlightWords: ['1-word trigger', 'low-friction'],
        stickerTags: [{ text: 'Zero Friction', color: 'blue' }],
        icons: ['🪩', '⚡'],
        swissHudMetadata: '03 // STEP 01 // 1-WORD TRIGGER',
        swipePrompt: 'STEP 2: THE 2-SECOND DM BOT →',
      },
      {
        slideType: 'step2',
        header: 'step 2: instant automated dm delivery in 2 seconds.',
        subhead: 'The robot sends the private link the exact millisecond they comment.',
        bodyBullets: [
          'Use OpenReply / ManyChat to listen for the trigger word',
          'Instantly reply to the comment: "Sent to your DMs! ✨ Check your inbox!"',
          'Send a friendly, high-value DM containing the direct interactive guide link',
        ],
        keyCallout: 'DELIVERY RULE: Instant speed (under 3 seconds) turns curiosity into immediate downloads.',
        badgeText: 'STEP 02: INSTANT DM',
        highlightWords: ['automated dm delivery', '2 seconds'],
        stickerTags: [{ text: 'Instant Reply', color: 'green' }],
        icons: ['🍒', '💸'],
        swissHudMetadata: '04 // STEP 02 // INSTANT DELIVERY',
        swipePrompt: 'STEP 3: THE HIGH-VALUE PLAYBOOK →',
      },
      {
        slideType: 'step3',
        header: 'step 3: interactive lead magnet with 1-click copy.',
        subhead: 'Give them so much undeniable free value they fall in love with your brand.',
        bodyBullets: [
          'Interactive web playbook with 1-click [📋 COPY PROMPT] buttons',
          'Clean luxury design matching project\\ciel Swiss HUD aesthetic',
          'Include a direct link to your shop / service at the bottom',
        ],
        keyCallout: 'VALUE RULE: Free value builds trust. Trust creates lifelong high-ticket buyers.',
        badgeText: 'STEP 03: FREE VALUE',
        highlightWords: ['interactive lead magnet', '1-click copy'],
        stickerTags: [{ text: '1-Click Copy', color: 'yellow' }],
        icons: ['⚡', '🖱️'],
        swissHudMetadata: '05 // STEP 03 // LEAD MAGNET',
        swipePrompt: 'THE AUTOMATION CHEAT SHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: 'the automated sales cheat sheet.',
        subhead: 'Save this simple 3-part blueprint for your next campaign:',
        bodyBullets: [
          '🎯 Carousel Post: Hook + 9-year-old clarity + free value recipe',
          '💬 1-Word CTA: Slide 8 asks for "POSTER" or "CIEL"',
          '🤖 DM Automation: OpenReply sends link in 2s flat',
          '📈 Conversion: Tracked sales and email captures on 100% autopilot',
        ],
        keyCallout: '💾 SAVE THIS POST: Build this automated funnel once, profit 24/7 forever!',
        badgeText: 'SAVEABLE CHEAT SHEET',
        highlightWords: ['sales cheat sheet', 'save this'],
        stickerTags: [{ text: '24/7 Funnel', color: 'green' }],
        icons: ['💾', '🍒'],
        swissHudMetadata: '06 // CHEAT SHEET // SALES FUNNEL',
        swipePrompt: 'THE 3-STEP SYSTEM →',
      },
      {
        slideType: 'summary',
        header: 'the complete autonomous conversion loop.',
        subhead: 'How to scale from 0 to 500 automated leads every week:',
        bodyBullets: [
          '1. Post daily reference-styled carousels',
          '2. Let the algorithm push your high-comment posts to new audiences',
          '3. Collect leads and sales continuously in your sleep',
        ],
        keyCallout: '✈️ SHARE WITH A CREATOR: Help someone stop wasting time with broken bio links!',
        badgeText: 'CONVERSION LOOP',
        highlightWords: ['autonomous conversion', 'scale to 500'],
        stickerTags: [{ text: 'Autopilot Engine', color: 'blue' }],
        icons: ['🚀', '⚡'],
        swissHudMetadata: '07 // SYSTEM // AUTOPILOT ENGINE',
        swipePrompt: 'CLAIM THE FREE FUNNEL BLUEPRINT →',
      },
      {
        slideType: 'cta',
        header: 'want the free automated dm funnel blueprint?',
        subhead: 'Drop a 1-word comment below and I will instantly DM you the complete setup guide!',
        bodyBullets: [
          '💬 Comment "SALES" on this post right now',
          '📥 Automated DM sends the complete 2-minute OpenReply setup guide + scripts',
          '🚀 Follow @junnbuilds / project\\ciel for daily visual directing & automation secrets',
        ],
        keyCallout: '⚡ Instant free delivery: Drop "SALES" below to get the download link.',
        badgeText: 'FREE PRIZE',
        highlightWords: ['funnel blueprint', 'free setup guide'],
        stickerTags: [{ text: 'Instant DM', color: 'pink' }],
        icons: ['🎁', '⚡', '🖱️'],
        swissHudMetadata: '08 // FREE PRIZE // DROP "SALES" BELOW',
        swipePrompt: 'COMMENT "SALES" NOW ↓',
      },
    ],
  },

  spring_physics_video: {
    topicTitle: 'How to Add Natural Spring Physics and Elastic Bounce to AI Videos',
    triggerWord: 'PHYSICS',
    captionHook: 'Why normal AI videos look stiff like a robot — and how spring physics fixes them.',
    slides: [
      {
        slideType: 'hook',
        header: 'why normal ai videos look stiff like a robot.',
        subhead: 'And how adding natural spring physics and elastic bounce makes them feel physically real.',
        badgeText: 'PHYSICS FORMULA',
        highlightWords: ['stiff like a robot', 'spring physics'],
        stickerTags: [
          { text: 'Spring Math', color: 'green' },
          { text: 'Real Bounce', color: 'pink' },
        ],
        icons: ['🍒', '⚡', '🪩', '🖱️'],
        swissHudMetadata: '01 // PHYSICS // MOTION DIRECTING',
        swipePrompt: 'THE ROBOT TRAP →',
      },
      {
        slideType: 'problem',
        header: 'the linear speed problem: zero gravity and zero inertia.',
        subhead: 'When an AI video moves in a flat straight line, your brain instantly detects the fake CGI.',
        bodyBullets: [
          'Real objects never move at constant speed',
          'When an object stops, it overshoots and bounces back into place',
          'Spring physics is what separates amateur AI clips from $100K luxury commercials',
        ],
        keyCallout: 'RULE: Natural overshoot and elastic settle is the secret to photoreal motion.',
        badgeText: 'THE LINEAR TRAP',
        highlightWords: ['zero gravity', 'fake cgi'],
        stickerTags: [{ text: 'Linear Trap', color: 'pink' }],
        icons: ['💸'],
        swissHudMetadata: '02 // THE PROBLEM // LINEAR MOTION',
        swipePrompt: 'SECRET 1: DAMPED SPRINGS →',
      },
      {
        slideType: 'step1',
        header: 'secret 1: the damped harmonic spring equation.',
        subhead: 'Use programmatic physics springs (mass, tension, friction) instead of flat keyframes.',
        bodyBullets: [
          'Mass: 1.0 (gives the hero object heavy physical presence)',
          'Tension: 180 (creates snappy, energetic response)',
          'Friction: 12 (smoothly absorbs the energy without shaking forever)',
        ],
        keyCallout: 'SPRING CODE: { mass: 1, tension: 180, friction: 12 } = juicy luxury settle.',
        badgeText: 'SECRET 01: SPRING MATH',
        highlightWords: ['damped harmonic', 'spring equation'],
        stickerTags: [{ text: 'Juicy Settle', color: 'blue' }],
        icons: ['🪩', '⚡'],
        swissHudMetadata: '03 // SECRET 01 // SPRING MATH',
        swipePrompt: 'SECRET 2: SPEED RAMPS →',
      },
      {
        slideType: 'step2',
        header: 'secret 2: non-uniform pacing & zero-g float.',
        subhead: 'Fast high-speed sprint resolving into weightless slow-motion.',
        bodyBullets: [
          'Frame 0-10: Explosive high-speed burst (creates adrenaline and grabs thumb)',
          'Frame 11-40: Smooth zero-G deceleration (allows viewer to admire luxury details)',
          'Contrast between fast and slow is what makes video hypnotic',
        ],
        keyCallout: 'PACING RULE: Fast explosion $\\rightarrow$ Slow weightless float $\\rightarrow$ Snappy snap.',
        badgeText: 'SECRET 02: PACING',
        highlightWords: ['non-uniform pacing', 'zero-g float'],
        stickerTags: [{ text: 'Speed Ramps', color: 'green' }],
        icons: ['🍒', '💸'],
        swissHudMetadata: '04 // SECRET 02 // SPEED RAMPS',
        swipePrompt: 'SECRET 3: VOLUMETRIC LIGHT →',
      },
      {
        slideType: 'step3',
        header: 'secret 3: volumetric raking light & caustics.',
        subhead: 'Lighting that reacts physically to the object as it moves through 3D space.',
        bodyBullets: [
          'Raking side key light creates deep shifting shadows across surfaces',
          'Ray-traced caustics project dancing light refractions onto background walls',
          '35mm film grain glues the lighting and physics together naturally',
        ],
        keyCallout: 'LIGHTING RULE: Shifting light shadows prove to the human eye that the 3D space is real.',
        badgeText: 'SECRET 03: RAKING LIGHT',
        highlightWords: ['volumetric light', 'caustics'],
        stickerTags: [{ text: 'Real Shadows', color: 'yellow' }],
        icons: ['⚡', '🖱️'],
        swissHudMetadata: '05 // SECRET 03 // VOLUMETRIC LIGHT',
        swipePrompt: 'THE PHYSICS CHEAT SHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: 'the spring physics cheat sheet.',
        subhead: 'Save this quick reference guide for Remotion & AI video prompts:',
        bodyBullets: [
          '🏎️ Snappy Button / Card: { mass: 0.5, tension: 300, friction: 18 }',
          '💎 Heavy Luxury Object: { mass: 2.0, tension: 120, friction: 14 }',
          '💧 Water Splash / Fluid: { mass: 0.8, tension: 220, friction: 8 }',
          '🎞️ Shutter Speed: 1/10,000s for crisp frozen micro-droplets',
        ],
        keyCallout: '💾 SAVE THIS POST: Copy-paste these exact physics spring values!',
        badgeText: 'SAVEABLE CHEAT SHEET',
        highlightWords: ['physics cheat sheet', 'save this'],
        stickerTags: [{ text: 'Spring Values', color: 'green' }],
        icons: ['💾', '🍒'],
        swissHudMetadata: '06 // CHEAT SHEET // SPRING VALUES',
        swipePrompt: 'THE COMPLETE CODE ENGINE →',
      },
      {
        slideType: 'summary',
        header: 'the 3-step programmatic cinema stack.',
        subhead: 'How to build $100K-looking motion commercials in code:',
        bodyBullets: [
          '1. Prompt with 50mm optical prime & raking key light',
          '2. Animate with damped harmonic spring physics',
          '3. Add sub-bass tactile sound effects for physical reality',
        ],
        keyCallout: '✈️ SHARE WITH A MOTION DESIGNER: Help someone fix their stiff robotic AI videos!',
        badgeText: 'CINEMA STACK',
        highlightWords: ['programmatic cinema', 'motion commercial'],
        stickerTags: [{ text: 'Code + Cinema', color: 'blue' }],
        icons: ['🚀', '⚡'],
        swissHudMetadata: '07 // SYSTEM // CODE + CINEMA',
        swipePrompt: 'CLAIM THE FREE CODE PACK →',
      },
      {
        slideType: 'cta',
        header: 'want the free remotion spring physics code pack?',
        subhead: 'Drop a 1-word comment below and I will instantly DM you the complete code templates!',
        bodyBullets: [
          '💬 Comment "PHYSICS" on this post right now',
          '📥 Automated DM sends all Remotion spring templates + Higgsfield camera codes in 2s',
          '🚀 Follow @junnbuilds / project\\ciel for daily AI directing secrets',
        ],
        keyCallout: '⚡ Instant free delivery: Drop "PHYSICS" below to get the download link.',
        badgeText: 'FREE PRIZE',
        highlightWords: ['spring physics code', 'free templates'],
        stickerTags: [{ text: 'Instant DM', color: 'pink' }],
        icons: ['🎁', '⚡', '🖱️'],
        swissHudMetadata: '08 // FREE PRIZE // DROP "PHYSICS" BELOW',
        swipePrompt: 'COMMENT "PHYSICS" NOW ↓',
      },
    ],
  },
  brand_transformation_story: {
    topicTitle: 'Nobody Remembers Your Origin Story. They Remember The Transformation.',
    triggerWord: 'STORY',
    captionHook: 'Nobody remembers your founding story. They remember the transformation they got to be part of.',
    slides: [
      {
        slideType: 'hook',
        header: 'Your brand needs to tell a story.',
        subhead: 'Why origin stories fail, and how customer transformations build billion-dollar brands.',
        badgeText: 'BRAND STORYTELLING',
        highlightWords: ['brand', 'story'],
        stickerTags: [{ text: 'Transformation Arc', color: 'pink' }],
        icons: ['📖', '⚡', '🏛️'],
        swissHudMetadata: '01 // BRAND STORY // SPEC 2026',
        swipePrompt: 'SWIPE FOR THE STORY →',
      },
      {
        slideType: 'problem',
        header: 'Most brands tell a story about themselves.',
        subhead: 'Founder journey. Company values. How it all started.',
        bodyBullets: [
          'Founders spend 10 minutes talking about their childhood garage ideas',
          'Audiences scroll past self-centered origin timelines',
          'People do not buy who you were; they buy who they become with you',
        ],
        keyCallout: "Customers don't care how you got here. They care whether they see themselves in what happens next.",
        badgeText: 'THE ORIGIN TRAP',
        highlightWords: ['about themselves', 'see themselves'],
        stickerTags: [{ text: 'The Mistake', color: 'pink' }],
        icons: ['⚠️', '📉'],
        swissHudMetadata: '02 // THE ORIGIN TRAP',
        swipePrompt: 'THE 10-MINUTE PITCH →',
      },
      {
        slideType: 'step1',
        header: 'The 10-Minute Origin Pitch Trap',
        subhead: 'A founder once opened a pitch with 10 minutes on his origin story.',
        bodyBullets: [
          'The investors checked out by minute two',
          'They wanted to know what changes for the customer, not for him',
          'Shift the spotlight from your biography to the buyer’s transformation',
        ],
        keyCallout: 'RULE: The customer is always Luke Skywalker. You are Yoda.',
        badgeText: 'SECRET 1',
        highlightWords: ['origin pitch', 'spotlight'],
        stickerTags: [{ text: 'Pivot', color: 'green' }],
        icons: ['🎯', '💡'],
        swissHudMetadata: '03 // PIVOT THE HERO',
        swipePrompt: 'WHAT ACTUALLY SELLS →',
      },
      {
        slideType: 'step2',
        header: "The story that actually sells isn't about your history.",
        subhead: 'It is a before and after transformation map.',
        bodyBullets: [
          'Who someone was before they discovered you',
          'Who they become after they experience your product',
          'Every marketing touchpoint must sit somewhere on that line',
        ],
        keyCallout: 'TRANSFORMATION FORMULA: Before State (Frustrated & Stuck) → After State (Empowered & Transformed).',
        badgeText: 'SECRET 2',
        highlightWords: ['before and after', 'transformation'],
        stickerTags: [{ text: 'Core Formula', color: 'blue' }],
        icons: ['🔥', '✨'],
        swissHudMetadata: '04 // BEFORE & AFTER',
        swipePrompt: 'THE MISSING INGREDIENT →',
      },
      {
        slideType: 'step3',
        header: "Most 'brand stories' skip the tension entirely.",
        subhead: 'No conflict. No stakes. No reason to keep watching.',
        bodyBullets: [
          'Without real tension, a story is just a dry chronological timeline',
          'Show the obstacle, the frustration, the high-stakes friction',
          'When tension is resolved, trust and loyalty are unlocked',
        ],
        keyCallout: 'NARRATIVE LAW: A story without a problem is just a timeline.',
        badgeText: 'SECRET 3',
        highlightWords: ['skip the tension', 'stakes'],
        stickerTags: [{ text: 'Tension & Stakes', color: 'yellow' }],
        icons: ['⚡', '🎬'],
        swissHudMetadata: '05 // NARRATIVE LAW',
        swipePrompt: 'THE GOLDEN PUNCHLINE →',
      },
      {
        slideType: 'cheatsheet',
        header: 'Nobody remembers your founding story.',
        subhead: 'They remember the transformation they got to be part of.',
        bodyBullets: [
          '1. Hook: Agitate their current unresolved problem',
          '2. Mirror: Reflect the internal frustration they feel daily',
          '3. Guide: Offer the proven vehicle and actionable path forward',
          '4. Identity: Celebrate the new identity they step into',
        ],
        keyCallout: '💾 SAVE THIS POST: The 4-Part Brand Transformation Architecture.',
        badgeText: 'THE CHEAT SHEET',
        highlightWords: ['transformation', 'got to be part of'],
        stickerTags: [{ text: 'Save This Arc', color: 'green' }],
        icons: ['💾', '🏛️'],
        swissHudMetadata: '06 // TRANSFORMATION CHEATSHEET',
        swipePrompt: 'THE 3-STEP FRAMEWORK →',
      },
      {
        slideType: 'summary',
        header: 'The 3-Step Story Engine',
        subhead: 'How to write high-converting brand stories in under 5 minutes:',
        bodyBullets: [
          '1. Define the Old World (Pain, Friction, Antiquated methods)',
          '2. Introduce the Catalyst (The new vehicle, philosophy, or tool)',
          '3. Reveal the New World (Status elevation, speed, freedom)',
        ],
        keyCallout: '✈️ SHARE WITH A FOUNDER: Help someone stop telling boring origin stories!',
        badgeText: 'WORKFLOW',
        highlightWords: ['story engine', 'catalyst'],
        stickerTags: [{ text: 'Fast Framework', color: 'blue' }],
        icons: ['🚀', '📈'],
        swissHudMetadata: '07 // 3-STEP STORY ENGINE',
        swipePrompt: 'CLAIM THE STORY PLAYBOOK →',
      },
      {
        slideType: 'cta',
        header: 'Want a brand story people actually see themselves in?',
        subhead: 'All storytelling frameworks, prompt codes & breakdown guides are pinned in our Telegram group.',
        bodyBullets: [
          '💬 Drop "STORY" below to get the private Telegram VIP invite link',
          '📥 Complete Storytelling Playbook & 8K cinematic visual prompts delivered instantly',
          '🚀 Follow @junnbuilds / project\\ciel for daily creative directing breakdowns',
        ],
        keyCallout: '📲 Instant VIP Telegram Access: All raw prompt packs & Figma templates pinned inside.',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['brand story', 'see themselves in'],
        stickerTags: [{ text: 'Instant Access', color: 'pink' }],
        icons: ['🎁', '📲', '🚀'],
        swissHudMetadata: '08 // VIP ACCESS // DROP "STORY" BELOW',
        swipePrompt: 'COMMENT "STORY" NOW ↓',
      },
    ],
  },
  ciel_invisible_craft_story: {
    topicTitle: 'Why We Spent 3 Months Obsessed Over a 0.5-Second Animation: The Soul of Physical Luxury',
    triggerWord: 'CRAFT',
    captionHook: 'Anyone can generate pixels. But spectacle without soul is forgotten in three seconds. Story is what makes physical objects immortal.',
    slides: [
      {
        slideType: 'hook',
        header: 'why we spent 3 months obsessed over a 0.5-second animation.',
        subhead: 'Anyone can generate pixels. But spectacle without soul is forgotten in three seconds.',
        badgeText: 'CIEL DOCTRINE',
        highlightWords: ['0.5-second animation', 'soul'],
        stickerTags: [{ text: 'Physical Craft', color: 'blue' }],
        icons: ['⏳', '✨', '🏛️'],
        swissHudMetadata: '01 // THE INVISIBLE CRAFT // SPEC 2026.01',
        swipePrompt: 'SWIPE FOR THE CRAFT →',
      },
      {
        slideType: 'problem',
        header: 'The commodity trap: why 99% of AI visuals feel hollow.',
        subhead: 'Today, AI makes visual spectacle easy and cheap.',
        bodyBullets: [
          'Cheap 3D renders lack weight, friction, and tactile human connection',
          'Audiences scroll past generic glossy commercials without feeling anything',
          'When everything looks perfect, nothing feels real or valuable',
        ],
        keyCallout: 'LAW OF SOUL: Spectacle without emotional stakes is forgotten in 3 seconds.',
        badgeText: 'THE PROBLEM',
        highlightWords: ['feel hollow', 'tactile human connection'],
        stickerTags: [{ text: 'Plastic Sheen', color: 'pink' }],
        icons: ['⚠️', '📉'],
        swissHudMetadata: '02 // THE COMMODITY TRAP',
        swipePrompt: 'THE SENSORY SHIFT →',
      },
      {
        slideType: 'step1',
        header: 'Sensory physics: capturing real material weight.',
        subhead: 'Luxury is felt through physical resistance, gravity, and micro-texture.',
        bodyBullets: [
          'Fluted glass perfume bottles refracting raw morning light',
          'Heavy tailored Abyss Black wool catching natural directional shadows',
          'Authentic 35mm prime lens distortion and fine lived-in surface pores',
        ],
        keyCallout: 'RULE 1: Physical materiality — viscosity, fabric weave, glass refraction — creates the emotional anchor.',
        badgeText: 'SECRET 1',
        highlightWords: ['sensory physics', 'material weight'],
        stickerTags: [{ text: 'Physics First', color: 'green' }],
        icons: ['💎', '🔍'],
        swissHudMetadata: '03 // SENSORY ANCHORS',
        swipePrompt: 'THE 3-ACT SPINE →',
      },
      {
        slideType: 'step2',
        header: 'The 3-Act narrative spine behind every post.',
        subhead: 'Story is the only defensible commercial moat in an AI era.',
        bodyBullets: [
          'Act I (The Truth): Unspoken human tension or cultural friction',
          'Act II (The Struggle): Sensory discovery and suspended zero-G float',
          'Act III (The Resolve): The physical object lands as the emotional catalyst',
        ],
        keyCallout: 'NARRATIVE FRAMEWORK: Tension creates attention. The physical object delivers the transformation.',
        badgeText: 'SECRET 2',
        highlightWords: ['3-Act spine', 'commercial moat'],
        stickerTags: [{ text: '3-Act Arc', color: 'blue' }],
        icons: ['🎬', '📖'],
        swissHudMetadata: '04 // 3-ACT NARRATIVE SPINE',
        swipePrompt: 'THE AUTEUR LIGHTING →',
      },
      {
        slideType: 'step3',
        header: 'Auteur lighting: rejecting the commercial studio gloss.',
        subhead: 'Real cinema lighting embraces deep shadow wells and natural raking light.',
        bodyBullets: [
          'Abyss Black (#0A0A0C) shadow wells create dramatic negative space',
          'Directional raking light sculpts form without plastic AI sheen',
          'Subtle volumetric mist and 35mm grain add cinematic depth',
        ],
        keyCallout: 'LIGHTING LAW: Deep shadows give light its authority and prestige.',
        badgeText: 'SECRET 3',
        highlightWords: ['auteur lighting', 'deep shadow wells'],
        stickerTags: [{ text: 'Abyss Black', color: 'yellow' }],
        icons: ['💡', '🌑'],
        swissHudMetadata: '05 // AUTEUR LIGHTING DOCTRINE',
        swipePrompt: 'THE SAVEABLE SPEC →',
      },
      {
        slideType: 'cheatsheet',
        header: 'The project\\ciel visual directing cheat sheet.',
        subhead: 'Save this slide for your next luxury brand campaign:',
        bodyBullets: [
          '• Color Palette: Abyss Black (#0A0A0C) + Crisp White (#FFFFFF)',
          '• Typography: Playfair Display Serif + Swiss Archivo 300 HUD Stamps',
          '• Lens Doctrine: 35mm / 50mm prime, natural depth plane separation',
          '• Texture Rule: Flattering-realism ceiling, fine lived-in pores, fabric weave',
        ],
        keyCallout: '💾 SAVE THIS POST: The Master Physical Luxury Directing Formula.',
        badgeText: 'THE CHEAT SHEET',
        highlightWords: ['directing cheat sheet', 'luxury brand formula'],
        stickerTags: [{ text: 'Save This Matrix', color: 'green' }],
        icons: ['💾', '🏛️'],
        swissHudMetadata: '06 // MASTER DIRECTING SPEC',
        swipePrompt: 'THE 3-MINUTE WORKFLOW →',
      },
      {
        slideType: 'summary',
        header: 'The 3-Minute Auteur Directing Workflow',
        subhead: 'How to build high-status brand stories with Banana Pro Director 3.0:',
        bodyBullets: [
          '1. Lock the physical object reference (glass, titanium, tailored textile)',
          '2. Set directional raking light and 35mm anamorphic camera framing',
          '3. Layer Swiss HUD metadata and high-contrast Playfair serif typography',
        ],
        keyCallout: '✈️ SHARE WITH A CREATOR: Help someone elevate their visual craft today!',
        badgeText: 'WORKFLOW',
        highlightWords: ['auteur workflow', 'physical object'],
        stickerTags: [{ text: 'Fast Workflow', color: 'blue' }],
        icons: ['🚀', '📈'],
        swissHudMetadata: '07 // AUTEUR WORKFLOW',
        swipePrompt: 'CLAIM THE MASTER PLAYBOOK →',
      },
      {
        slideType: 'cta',
        header: 'Want the master project\\ciel brand directing playbook?',
        subhead: 'All storytelling frameworks, prompt codes & breakdown guides are pinned in our Telegram group.',
        bodyBullets: [
          '💬 Drop "CRAFT" below to get the private Telegram VIP invite link',
          '📥 Complete Storytelling Directing Playbook & 8K cinema prompt swipe file',
          '🚀 Follow @junnbuilds / project\\ciel for daily auteur directing breakdowns',
        ],
        keyCallout: '📲 Instant VIP Telegram Access: All raw prompt packs & Figma templates pinned inside.',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['directing playbook', 'Telegram VIP'],
        stickerTags: [{ text: 'Instant Access', color: 'pink' }],
        icons: ['🎁', '📲', '🚀'],
        swissHudMetadata: '08 // VIP ACCESS // DROP "CRAFT" BELOW',
        swipePrompt: 'COMMENT "CRAFT" NOW ↓',
      },
    ],
  },
  ciel_uncanny_luxury_story: {
    topicTitle: 'Why Billion-Dollar Fashion Houses Shoot Luxury In Raw Subways: The Law of Uncanny Juxtaposition',
    triggerWord: 'JUXTA',
    captionHook: 'When you put luxury inside a sterile white studio, it looks like an ad. When you put luxury in a gritty raw subway, it looks like art.',
    slides: [
      {
        slideType: 'hook',
        header: 'why billion-dollar fashion houses shoot luxury in raw subways.',
        subhead: 'The secret psychological weapon behind Balenciaga, Jacquemus, and project\\ciel.',
        badgeText: 'VISUAL PSYCHOLOGY',
        highlightWords: ['raw subways', 'uncanny juxtaposition'],
        stickerTags: [{ text: 'Pattern Interrupt', color: 'pink' }],
        icons: ['🚇', '💎', '🏛️'],
        swissHudMetadata: '01 // UNCANNY JUXTAPOSITION // SPEC 2026.01',
        swipePrompt: 'SWIPE FOR THE PSYCHOLOGY →',
      },
      {
        slideType: 'problem',
        header: 'The sterile studio paradox: why ordinary ads get ignored.',
        subhead: 'When luxury is presented in expected environments, the brain tunes it out.',
        bodyBullets: [
          'White seamless studio backdrops scream "I am trying to sell you something"',
          'Viewers have developed subconscious ad blindness to polished commercial setups',
          'Predictable compositions never trigger curiosity or emotional pause',
        ],
        keyCallout: 'THE PARADOX: Predictable elegance is invisible. Unexpected contrast demands attention.',
        badgeText: 'THE PROBLEM',
        highlightWords: ['sterile studio', 'ad blindness'],
        stickerTags: [{ text: 'Ad Blindness', color: 'pink' }],
        icons: ['⚠️', '📉'],
        swissHudMetadata: '02 // THE STERILE PARADOX',
        swipePrompt: 'THE JUXTAPOSITION LAW →',
      },
      {
        slideType: 'step1',
        header: 'Law of Uncanny Juxtaposition: colliding opposites.',
        subhead: 'Place impossible luxury and elegance inside raw, gritty environments.',
        bodyBullets: [
          'A guy ironing an haute-couture shirt inside an active underground subway car',
          'A sculptural glass perfume flacon resting on wet industrial construction scaffolding',
          'A tailored silk trench coat moving through rainy brutalist concrete architecture',
        ],
        keyCallout: 'RULE 1: High Culture + Raw Reality = Irresistible Cultural Gravity.',
        badgeText: 'SECRET 1',
        highlightWords: ['colliding opposites', 'cultural gravity'],
        stickerTags: [{ text: 'Juxtaposition', color: 'green' }],
        icons: ['⚡', '🏙️'],
        swissHudMetadata: '03 // COLLIDING OPPOSITES',
        swipePrompt: 'THE TENSION FORMULA →',
      },
      {
        slideType: 'step2',
        header: 'How contrast creates instant status & intrigue.',
        subhead: 'The juxtaposition forces the viewer to invent a backstory.',
        bodyBullets: [
          'The viewer asks: "Why is that luxury object there? What happened before?"',
          'Curiosity triggers engagement time, boosting algorithmic reach by 3.4x',
          'The brand is perceived as an avant-garde cultural auteur, not a pushy vendor',
        ],
        keyCallout: 'PSYCHOLOGICAL MECHANISM: Curiosity gaps turn casual scrollers into engaged story decoders.',
        badgeText: 'SECRET 2',
        highlightWords: ['curiosity gap', 'avant-garde'],
        stickerTags: [{ text: 'Curiosity Engine', color: 'blue' }],
        icons: ['🧠', '🔍'],
        swissHudMetadata: '04 // CURIOSITY ENGINE',
        swipePrompt: 'THE CAMERA FORMULA →',
      },
      {
        slideType: 'step3',
        header: 'The 35mm Prime Camera Setup for Juxtaposition.',
        subhead: 'Use Banana Pro Director 3.0 cinema doctrine to capture the shot:',
        bodyBullets: [
          '• 35mm / 50mm Prime lens with subtle environmental wide perspective',
          '• Shallow depth of field keeping the luxury subject in sharp focus',
          '• Natural ambient environmental light mixed with soft directional key',
        ],
        keyCallout: 'PROMPT KEYWORD: "Uncanny juxtaposition, 35mm prime cinema plate, raw brutalist environment, hyper-refined luxury subject."',
        badgeText: 'SECRET 3',
        highlightWords: ['35mm prime', 'Banana Pro Director'],
        stickerTags: [{ text: 'Camera Setup', color: 'yellow' }],
        icons: ['📸', '🎬'],
        swissHudMetadata: '05 // CAMERA RECIPE',
        swipePrompt: 'THE SAVEABLE CHEATSHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: 'The Uncanny Juxtaposition Cheat Sheet.',
        subhead: 'Save this matrix for your next creative campaign:',
        bodyBullets: [
          '• High-Fashion Tailoring + Underground Subway / Brutalist Alley',
          '• Sculpted Glass Perfume + Weathered Scaffolding / Wet Concrete',
          '• Monolithic Chrome Hardware + Misty Morning Parisian Street',
          '• Heavy Wool Overcoat + Tropical Resort Palm Umbrellas',
        ],
        keyCallout: '💾 SAVE THIS POST: The 4 Juxtaposition Archetypes That Command Attention.',
        badgeText: 'THE CHEAT SHEET',
        highlightWords: ['juxtaposition matrix', 'archetypes'],
        stickerTags: [{ text: 'Save This Formula', color: 'green' }],
        icons: ['💾', '🏛️'],
        swissHudMetadata: '06 // JUXTAPOSITION MATRIX',
        swipePrompt: 'THE 3-STEP WORKFLOW →',
      },
      {
        slideType: 'summary',
        header: 'The 3-Step Juxtaposition Engine',
        subhead: 'How to direct world-class luxury visuals in 3 minutes:',
        bodyBullets: [
          '1. Pick your luxury hero object / subject (Ciel fluted glass, silk, tailored coat)',
          '2. Select a high-friction contrasting location (Subway, construction, rain alley)',
          '3. Apply Banana Pro Director 3.0 photorealism with Swiss HUD framing',
        ],
        keyCallout: '✈️ SHARE WITH A DESIGNER: Show someone the power of unexpected contrast!',
        badgeText: 'WORKFLOW',
        highlightWords: ['juxtaposition engine', 'contrasting location'],
        stickerTags: [{ text: 'Fast Engine', color: 'blue' }],
        icons: ['🚀', '📈'],
        swissHudMetadata: '07 // 3-STEP ENGINE',
        swipePrompt: 'CLAIM THE FULL PLAYBOOK →',
      },
      {
        slideType: 'cta',
        header: 'Want the full project\\ciel visual directing swipe file?',
        subhead: 'All storytelling frameworks, prompt codes & breakdown guides are pinned in our Telegram group.',
        bodyBullets: [
          '💬 Drop "JUXTA" below to get the private Telegram VIP invite link',
          '📥 Complete Juxtaposition Storytelling Guide & 8K prompt swipe file',
          '🚀 Follow @junnbuilds / project\\ciel for daily creative directing breakdowns',
        ],
        keyCallout: '📲 Instant VIP Telegram Access: All raw prompt packs & Figma templates pinned inside.',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['visual directing swipe file', 'Telegram VIP'],
        stickerTags: [{ text: 'Instant Access', color: 'pink' }],
        icons: ['🎁', '📲', '🚀'],
        swissHudMetadata: '08 // VIP ACCESS // DROP "JUXTA" BELOW',
        swipePrompt: 'COMMENT "JUXTA" NOW ↓',
      },
    ],
  },
  founder_origin_reframe: {
    topicTitle: 'Why Great Founders Never Pitch What They Built: The Psychology of Visionary Stories',
    triggerWord: 'FOUNDER',
    captionHook: 'Nobody cares about your resume or your technology stack. They care whether you understand their struggle.',
    slides: [
      {
        slideType: 'hook',
        header: 'Your pitch is losing everyone in minute two.',
        subhead: 'You are talking about features and architecture. They want to know what changes for them.',
        badgeText: 'FOUNDER STORY DOCTRINE',
        highlightWords: ['losing everyone', 'minute two'],
        stickerTags: [{ text: 'Founder Arc', color: 'blue' }],
        icons: ['⚡', '🎙️', '🏛️'],
        swissHudMetadata: '01 // FOUNDER NARRATIVE // SPEC 2026.01',
        swipePrompt: 'SWIPE FOR THE REFRAME →',
      },
      {
        slideType: 'problem',
        header: 'Most founders explain what they built.',
        subhead: 'Line items. Product modules. Tech stack. Pricing tiers.',
        bodyBullets: [
          'Investors and customers tune out when presented with cold specifications',
          'Features explain function; stories unlock emotional buy-in',
          'When you pitch the tool, you compete on price; when you pitch the mission, you are untouchable',
        ],
        keyCallout: 'LAW OF DESIRE: People do not buy software; they buy a better version of themselves.',
        badgeText: 'THE MISTAKE',
        highlightWords: ['cold specifications', 'emotional buy-in'],
        stickerTags: [{ text: 'The Pitch Trap', color: 'pink' }],
        icons: ['⚠️', '📉'],
        swissHudMetadata: '02 // THE PITCH TRAP',
        swipePrompt: 'THE VISIONARY SHIFT →',
      },
      {
        slideType: 'step1',
        header: 'Steve Jobs did not sell 5GB of storage.',
        subhead: 'He sold "1,000 songs in your pocket."',
        bodyBullets: [
          'He skipped the hard drive revolutions per minute entirely',
          'He framed the entire product through the lens of human experience',
          'The customer immediately visualized their morning commute transformed',
        ],
        keyCallout: 'RULE 1: Translate every technical feature into a lived human moment.',
        badgeText: 'SECRET 1',
        highlightWords: ['1000 songs', 'human moment'],
        stickerTags: [{ text: 'Human Lens', color: 'green' }],
        icons: ['🎧', '✨'],
        swissHudMetadata: '03 // TRANSLATE THE FEATURE',
        swipePrompt: 'THE NARRATIVE ARC →',
      },
      {
        slideType: 'step2',
        header: 'The 3-Act Founder Narrative Spine.',
        subhead: 'Structure every pitch and campaign around this simple line:',
        bodyBullets: [
          'Act I (The Broken Old World): The unspoken friction everyone accepts',
          'Act II (The Epiphany): The insight that made the old way unacceptable',
          'Act III (The New Identity): Who the customer becomes with this vehicle',
        ],
        keyCallout: 'NARRATIVE FRAMEWORK: The founder is not the hero. The customer is the hero; the founder is the guide.',
        badgeText: 'SECRET 2',
        highlightWords: ['broken old world', 'customer is the hero'],
        stickerTags: [{ text: 'Hero Arc', color: 'blue' }],
        icons: ['🗺️', '🎬'],
        swissHudMetadata: '04 // HERO ARCHITECTURE',
        swipePrompt: 'THE STAKES & TENSION →',
      },
      {
        slideType: 'step3',
        header: "Most founder stories skip the sacrifice.",
        subhead: 'Without friction, victory feels unearned and forgettable.',
        bodyBullets: [
          'Share the moments where the project almost died',
          'Vulnerability creates trust faster than polished perfection',
          'True authority is built on scars, not corporate press releases',
        ],
        keyCallout: 'NARRATIVE APHORISM: A founder story without sacrifice is just corporate PR.',
        badgeText: 'SECRET 3',
        highlightWords: ['sacrifice', 'vulnerability'],
        stickerTags: [{ text: 'True Authority', color: 'yellow' }],
        icons: ['🔥', '⚔️'],
        swissHudMetadata: '05 // SCARS OVER POLISH',
        swipePrompt: 'THE UNIVERSAL LAW →',
      },
      {
        slideType: 'cheatsheet',
        header: 'Nobody buys your product.',
        subhead: 'They buy the future you make possible for them.',
        bodyBullets: [
          '1. Hook: Mirror their existing daily frustration',
          '2. Contrast: Prove why existing solutions are broken',
          '3. Weapon: Hand them the new vehicle to win',
          '4. Transformation: Celebrate their new elevated status',
        ],
        keyCallout: '💾 SAVE THIS POST: The Master Founder Storytelling Matrix.',
        badgeText: 'THE CHEAT SHEET',
        highlightWords: ['future possible', 'transformation'],
        stickerTags: [{ text: 'Save This Arc', color: 'green' }],
        icons: ['💾', '🏛️'],
        swissHudMetadata: '06 // FOUNDER MATRIX',
        swipePrompt: 'THE 3-MINUTE BLUEPRINT →',
      },
      {
        slideType: 'cta',
        header: 'Want a founder story that commands investor & customer loyalty?',
        subhead: 'All founder pitch frameworks, prompt codes & breakdown guides are pinned in our Telegram group.',
        bodyBullets: [
          '💬 Drop "FOUNDER" below to get the private Telegram VIP invite link',
          '📥 Complete Visionary Founder Playbook & 8K cinema prompt swipe file',
          '🚀 Follow @junnbuilds / project\\ciel for daily visual storytelling breakdowns',
        ],
        keyCallout: '📲 Instant VIP Telegram Access: All raw prompt packs & Figma templates pinned inside.',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['founder story', 'Telegram VIP'],
        stickerTags: [{ text: 'Instant Access', color: 'pink' }],
        icons: ['🎁', '📲', '🚀'],
        swissHudMetadata: '07 // VIP ACCESS // DROP "FOUNDER" BELOW',
        swipePrompt: 'COMMENT "FOUNDER" NOW ↓',
      },
    ],
  },
  visual_directing_cinema_story: {
    topicTitle: 'How Cinema Lighting & Negative Space Create Subconscious Luxury Value',
    triggerWord: 'CINEMA',
    captionHook: 'Cheap visuals flood the frame with light. Auteur cinema uses deep shadow wells to make the light valuable.',
    slides: [
      {
        slideType: 'hook',
        header: 'Why cheap visuals look fake in three seconds.',
        subhead: 'When you eliminate shadows, you eliminate drama, mystery, and perceived luxury.',
        badgeText: 'CINEMA DOCTRINE',
        highlightWords: ['cheap visuals', 'eliminate shadows'],
        stickerTags: [{ text: 'Cinema Stack', color: 'blue' }],
        icons: ['🎥', '💡', '🏛️'],
        swissHudMetadata: '01 // CINEMA LIGHTING // SPEC 2026.01',
        swipePrompt: 'SWIPE FOR THE LIGHTING LAW →',
      },
      {
        slideType: 'problem',
        header: 'The flat studio lighting trap.',
        subhead: '99% of digital creators light their scenes like an office cafeteria.',
        bodyBullets: [
          'Even, uniform lighting destroys depth planes and material texture',
          'Audiences perceive flat lighting as cheap, corporate, and synthetic',
          'Prestige brands use chiaroscuro: high-contrast directional raking light',
        ],
        keyCallout: 'LAW OF CONTRAST: Deep Abyss Black shadows give light its authority and prestige.',
        badgeText: 'THE PROBLEM',
        highlightWords: ['flat lighting', 'chiaroscuro'],
        stickerTags: [{ text: 'The Flat Trap', color: 'pink' }],
        icons: ['⚠️', '📉'],
        swissHudMetadata: '02 // THE FLAT TRAP',
        swipePrompt: 'THE 35MM CINEMA STACK →',
      },
      {
        slideType: 'step1',
        header: 'The 35mm Prime Lens Doctrine.',
        subhead: 'Why optical distortion and prime framing create cinematic reality:',
        bodyBullets: [
          '• 35mm / 50mm Prime lens creates natural human eye perspective',
          '• Subtle barrel distortion and optical falloff anchor the frame',
          '• Fine lived-in surface pores and authentic 35mm film grain',
        ],
        keyCallout: 'RULE 1: Reject perfect digital lenses; embrace optical glass texture.',
        badgeText: 'SECRET 1',
        highlightWords: ['35mm prime', 'optical texture'],
        stickerTags: [{ text: 'Optical Glass', color: 'green' }],
        icons: ['📸', '✨'],
        swissHudMetadata: '03 // OPTICAL GLASS',
        swipePrompt: 'THE SHADOW DOCTRINE →',
      },
      {
        slideType: 'step2',
        header: 'Raking directional key light.',
        subhead: 'How raking angles sculpt physical form without CGI sheen:',
        bodyBullets: [
          'Light placed at 75-85 degrees rakes across surfaces to reveal micro-texture',
          'Fluted glass perfume bottles catch authentic caustics and refractions',
          'Tailored dark wool outerwear absorbs light with deep matte richness',
        ],
        keyCallout: 'CINEMA FORMULA: Directional raking key + deep shadow wells = instant luxury authority.',
        badgeText: 'SECRET 2',
        highlightWords: ['raking key light', 'shadow wells'],
        stickerTags: [{ text: 'Raking Light', color: 'blue' }],
        icons: ['💡', '🎬'],
        swissHudMetadata: '04 // RAKING ANGLE',
        swipePrompt: 'THE NEGATIVE SPACE RULE →',
      },
      {
        slideType: 'step3',
        header: 'Negative space is where status lives.',
        subhead: 'Insecure brands clutter the canvas; luxury houses leave room to breathe.',
        bodyBullets: [
          'Abyss Black negative space creates an atmospheric vacuum',
          'The viewer’s gaze is effortlessly guided to the single hero subject',
          'Simplicity signals extreme confidence and scarcity',
        ],
        keyCallout: 'DESIGN APHORISM: Clutter signals panic. Negative space signals dominance.',
        badgeText: 'SECRET 3',
        highlightWords: ['negative space', 'status lives'],
        stickerTags: [{ text: 'Negative Space', color: 'yellow' }],
        icons: ['🖤', '🌌'],
        swissHudMetadata: '05 // NEGATIVE SPACE',
        swipePrompt: 'THE SAVEABLE SPEC →',
      },
      {
        slideType: 'cheatsheet',
        header: 'The Cinema Visual Directing Cheat Sheet.',
        subhead: 'Save this recipe for your next visual campaign:',
        bodyBullets: [
          '• Palette: Abyss Black (#0A0A0C) + Studio Slate (#141418) + Amber Glow',
          '• Lighting: Directional raking key at 80 degrees, deep shadow wells',
          '• Lens: 35mm / 50mm anamorphic prime with fine 35mm film grain',
          '• Texture: Lived-in pore detail, physical fabric weave, zero CGI sheen',
        ],
        keyCallout: '💾 SAVE THIS POST: The Master Cinema Directing Matrix.',
        badgeText: 'THE CHEAT SHEET',
        highlightWords: ['directing matrix', 'recipe'],
        stickerTags: [{ text: 'Save This Matrix', color: 'green' }],
        icons: ['💾', '🏛️'],
        swissHudMetadata: '06 // CINEMA DIRECTING SPEC',
        swipePrompt: 'THE 3-MINUTE WORKFLOW →',
      },
      {
        slideType: 'cta',
        header: 'Want the master cinema visual directing swipe file?',
        subhead: 'All lighting codes, 8K prompt formulas & breakdown guides are pinned in our Telegram group.',
        bodyBullets: [
          '💬 Drop "CINEMA" below to get the private Telegram VIP invite link',
          '📥 Complete Cinema Directing Playbook & 8K prompt swipe file',
          '🚀 Follow @junnbuilds / project\\ciel for daily visual storytelling breakdowns',
        ],
        keyCallout: '📲 Instant VIP Telegram Access: All raw prompt packs & Figma templates pinned inside.',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['cinema swipe file', 'Telegram VIP'],
        stickerTags: [{ text: 'Instant Access', color: 'pink' }],
        icons: ['🎁', '📲', '🚀'],
        swissHudMetadata: '07 // VIP ACCESS // DROP "CINEMA" BELOW',
        swipePrompt: 'COMMENT "CINEMA" NOW ↓',
      },
    ],
  },
  transformation_framework_story: {
    topicTitle: 'The 3-Act Hero Arc: The Only Storytelling Formula That Never Ages',
    triggerWord: 'HERO',
    captionHook: 'From ancient myths to billion-dollar product launches, every story that moves people follows the exact same 3-act spine.',
    slides: [
      {
        slideType: 'hook',
        header: 'Every story that moved you followed this exact spine.',
        subhead: 'You do not need to reinvent narrative psychology. You just need to master this 3-act line.',
        badgeText: 'THE 3-ACT SPINE',
        highlightWords: ['moved you', '3-act spine'],
        stickerTags: [{ text: 'Hero Formula', color: 'blue' }],
        icons: ['📜', '⚡', '🏛️'],
        swissHudMetadata: '01 // THE HERO ARC // SPEC 2026.01',
        swipePrompt: 'SWIPE FOR THE 3 ACTS →',
      },
      {
        slideType: 'problem',
        header: 'Why most content dies in the newsfeed.',
        subhead: 'Linear descriptions put audiences to sleep because there is zero emotional velocity.',
        bodyBullets: [
          'Listing tips or features without narrative stakes is forgotten in seconds',
          'Humans are biologically hardwired to remember characters navigating conflict',
          'When you structure your post as a transformation, retention triples',
        ],
        keyCallout: 'PSYCHOLOGY LAW: Information tells. Transformation sells.',
        badgeText: 'THE PROBLEM',
        highlightWords: ['emotional velocity', 'transformation sells'],
        stickerTags: [{ text: 'The Retention Trap', color: 'pink' }],
        icons: ['⚠️', '📉'],
        swissHudMetadata: '02 // THE RETENTION TRAP',
        swipePrompt: 'ACT I: THE TENSION →',
      },
      {
        slideType: 'step1',
        header: 'Act I: The Unspoken Tension.',
        subhead: 'Open by naming the hidden frustration everyone feels but nobody articulates:',
        bodyBullets: [
          'State the painful status quo in clear, empathetic terms',
          'Make the audience say: "That is exactly what happened to me this morning"',
          'Tension creates the psychological open loop that forces them to read on',
        ],
        keyCallout: 'RULE 1: If you do not hook them with tension in Act I, Act II and III will never be read.',
        badgeText: 'SECRET 1',
        highlightWords: ['unspoken tension', 'open loop'],
        stickerTags: [{ text: 'Act I: Tension', color: 'green' }],
        icons: ['🎣', '✨'],
        swissHudMetadata: '03 // ACT I: TENSION',
        swipePrompt: 'ACT II: THE STRUGGLE →',
      },
      {
        slideType: 'step2',
        header: 'Act II: The Sensory Struggle.',
        subhead: 'Show the friction of trying and failing with the old broken methods:',
        bodyBullets: [
          'Reveal why conventional advice fails in the real world',
          'Take the reader through the moment of confusion and search',
          'Build suspense right before the breakthrough discovery',
        ],
        keyCallout: 'RULE 2: The bigger the struggle in Act II, the higher the perceived value of your solution.',
        badgeText: 'SECRET 2',
        highlightWords: ['sensory struggle', 'suspense'],
        stickerTags: [{ text: 'Act II: Struggle', color: 'blue' }],
        icons: ['⚡', '🎬'],
        swissHudMetadata: '04 // ACT II: STRUGGLE',
        swipePrompt: 'ACT III: TRANSFORMATION →',
      },
      {
        slideType: 'step3',
        header: 'Act III: The New Identity.',
        subhead: 'Introduce the catalyst and reveal who the protagonist becomes:',
        bodyBullets: [
          'The solution is not a set of checkboxes; it is a permanent identity upgrade',
          'Paint the clear contrast between who they were before and who they are now',
          'Give them the simple next step to step into that new identity today',
        ],
        keyCallout: 'NARRATIVE LAW: A great story does not end with a product; it ends with a transformed human.',
        badgeText: 'SECRET 3',
        highlightWords: ['new identity', 'transformed human'],
        stickerTags: [{ text: 'Act III: Identity', color: 'yellow' }],
        icons: ['👑', '🌟'],
        swissHudMetadata: '05 // ACT III: IDENTITY',
        swipePrompt: 'THE SAVEABLE CHEATSHEET →',
      },
      {
        slideType: 'cheatsheet',
        header: 'The 3-Act Hero Storytelling Cheat Sheet.',
        subhead: 'Save this template for your next carousel or campaign:',
        bodyBullets: [
          '• Act I: The Unspoken Tension (Agitate status quo)',
          '• Act II: The Sensory Struggle (Reveal conventional failure)',
          '• Act III: The Transformation (Introduce catalyst & new identity)',
        ],
        keyCallout: '💾 SAVE THIS POST: The Universal 3-Act Storytelling Engine.',
        badgeText: 'THE CHEAT SHEET',
        highlightWords: ['storytelling engine', 'template'],
        stickerTags: [{ text: 'Save This Engine', color: 'green' }],
        icons: ['💾', '🏛️'],
        swissHudMetadata: '06 // 3-ACT CHEAT SHEET',
        swipePrompt: 'CLAIM THE STORY PLAYBOOK →',
      },
      {
        slideType: 'cta',
        header: 'Want the master 3-Act Storytelling Playbook?',
        subhead: 'All narrative templates, prompt codes & breakdown guides are pinned in our Telegram group.',
        bodyBullets: [
          '💬 Drop "HERO" below to get the private Telegram VIP invite link',
          '📥 Complete 3-Act Storytelling Guide & 8K cinema prompt swipe file',
          '🚀 Follow @junnbuilds / project\\ciel for daily visual storytelling breakdowns',
        ],
        keyCallout: '📲 Instant VIP Telegram Access: All raw prompt packs & Figma templates pinned inside.',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['hero playbook', 'Telegram VIP'],
        stickerTags: [{ text: 'Instant Access', color: 'pink' }],
        icons: ['🎁', '📲', '🚀'],
        swissHudMetadata: '07 // VIP ACCESS // DROP "HERO" BELOW',
        swipePrompt: 'COMMENT "HERO" NOW ↓',
      },
    ],
  },
  auteur_cultural_moat_story: {
    topicTitle: 'When Everything Is Generated in 3 Seconds: Taste and Story Are The Only Moat',
    triggerWord: 'TASTE',
    captionHook: 'When tools become commodities, execution speed drops to zero. What separates eternal luxury from forgotten noise is taste.',
    slides: [
      {
        slideType: 'hook',
        header: 'When anyone can generate pixels, taste is the only moat.',
        subhead: 'AI made visual generation free. It made discerning art direction priceless.',
        badgeText: 'BRAND PHILOSOPHY',
        highlightWords: ['taste is the only moat', 'priceless'],
        stickerTags: [{ text: 'Taste Moat', color: 'blue' }],
        icons: ['🏛️', '✨', '⏳'],
        swissHudMetadata: '01 // THE TASTE MOAT // SPEC 2026.01',
        swipePrompt: 'SWIPE FOR THE PHILOSOPHY →',
      },
      {
        slideType: 'problem',
        header: 'The commodity deluge.',
        subhead: 'The internet is flooded with generic, glossy, synthetic AI content.',
        bodyBullets: [
          'When anyone can prompt a 3D render in 5 seconds, renders lose all value',
          'Audiences developed instant subconscious blindness to generic AI aesthetics',
          'What people crave today is tactile friction, material weight, and auteur vision',
        ],
        keyCallout: 'COMMODITY LAW: When supply approaches infinity, discernment becomes the only luxury.',
        badgeText: 'THE PROBLEM',
        highlightWords: ['commodity deluge', 'discernment'],
        stickerTags: [{ text: 'The AI Deluge', color: 'pink' }],
        icons: ['⚠️', '📉'],
        swissHudMetadata: '02 // THE COMMODITY DELUGE',
        swipePrompt: 'THE PILLARS OF TASTE →',
      },
      {
        slideType: 'step1',
        header: 'Pillar 1: Physical Materiality.',
        subhead: 'Anchor digital visuals into authentic physical sensory textures:',
        bodyBullets: [
          'Fluted crystal glass refractions, tailored heavyweight wool, brushed titanium',
          'Natural imperfect lighting that embraces deep shadow wells',
          'Lived-in skin textures and authentic 35mm film grain',
        ],
        keyCallout: 'RULE 1: If it looks like plastic 3D, it is forgotten. If it feels heavy, it commands respect.',
        badgeText: 'SECRET 1',
        highlightWords: ['physical materiality', 'tactile weight'],
        stickerTags: [{ text: 'Materiality', color: 'green' }],
        icons: ['💎', '🔍'],
        swissHudMetadata: '03 // MATERIALITY',
        swipePrompt: 'PILLAR 2: RESTRAINT →',
      },
      {
        slideType: 'step2',
        header: 'Pillar 2: Extreme Restraint.',
        subhead: 'Amateurs add more elements; masters remove until nothing more can be taken away:',
        bodyBullets: [
          'One dominant visual symbol or subject per composition',
          'Generous Abyss Black negative space that lets the subject command the room',
          'Restrained typography: crisp white editorial serif over photographic tone',
        ],
        keyCallout: 'AUTEUR LAW: Luxury is not what you add; it is what you have the discipline to withhold.',
        badgeText: 'SECRET 2',
        highlightWords: ['extreme restraint', 'discipline to withhold'],
        stickerTags: [{ text: 'Restraint', color: 'blue' }],
        icons: ['🖤', '🎬'],
        swissHudMetadata: '04 // EXTREME RESTRAINT',
        swipePrompt: 'PILLAR 3: CULTURAL NARRATIVE →',
      },
      {
        slideType: 'step3',
        header: 'Pillar 3: Cultural Narrative.',
        subhead: 'Every visual must carry an unspoken story and cultural point of view:',
        bodyBullets: [
          'Do not sell product specs; broadcast a cultural philosophy',
          'Align your brand with timeless human values: craft, courage, transformation',
          'Create artifacts that people want to save, study, and pass on',
        ],
        keyCallout: 'BRAND APHORISM: Products become obsolete. Cultural stories become mythology.',
        badgeText: 'SECRET 3',
        highlightWords: ['cultural narrative', 'mythology'],
        stickerTags: [{ text: 'Mythology', color: 'yellow' }],
        icons: ['📜', '👑'],
        swissHudMetadata: '05 // CULTURAL MYTHOLOGY',
        swipePrompt: 'THE SAVEABLE MANIFESTO →',
      },
      {
        slideType: 'cheatsheet',
        header: 'The Auteur Taste & Brand Moat Manifesto.',
        subhead: 'Save these 3 laws for building an enduring creative brand:',
        bodyBullets: [
          '1. Physical Materiality: Lived-in textures over plastic CGI',
          '2. Extreme Restraint: Silence and negative space command status',
          '3. Cultural Narrative: Turn your product into a transformative vehicle',
        ],
        keyCallout: '💾 SAVE THIS POST: The 3 Pillars of an Indestructible Brand Moat.',
        badgeText: 'THE CHEAT SHEET',
        highlightWords: ['manifesto', 'brand moat'],
        stickerTags: [{ text: 'Save Manifesto', color: 'green' }],
        icons: ['💾', '🏛️'],
        swissHudMetadata: '06 // TASTE MANIFESTO',
        swipePrompt: 'JOIN THE MOVEMENT →',
      },
      {
        slideType: 'cta',
        header: 'Want to master the art of auteur visual storytelling?',
        subhead: 'All taste frameworks, prompt codes & breakdown guides are pinned in our Telegram group.',
        bodyBullets: [
          '💬 Drop "TASTE" below to get the private Telegram VIP invite link',
          '📥 Complete Auteur Brand Directing Playbook & 8K prompt swipe file',
          '🚀 Follow @junnbuilds / project\\ciel for daily visual storytelling breakdowns',
        ],
        keyCallout: '📲 Instant VIP Telegram Access: All raw prompt packs & Figma templates pinned inside.',
        badgeText: 'TELEGRAM VIP ACCESS',
        highlightWords: ['auteur storytelling', 'Telegram VIP'],
        stickerTags: [{ text: 'Instant Access', color: 'pink' }],
        icons: ['🎁', '📲', '🚀'],
        swissHudMetadata: '07 // VIP ACCESS // DROP "TASTE" BELOW',
        swipePrompt: 'COMMENT "TASTE" NOW ↓',
      },
    ],
  },
};

/**
 * Builds structured carousel copy strictly focused on ONE SINGLE TOPIC.
 */
export function generateCarouselCopy(params: {
  topicKey?: SingleTopicKey;
  topic?: string;
  totalSlides?: number;
  brandHandle?: string;
}): CarouselCopyPackage {
  const { topicKey } = params;

  const topicKeys = Object.keys(SINGLE_TOPIC_CAROUSEL_BLUEPRINTS) as SingleTopicKey[];
  const selectedKey: SingleTopicKey = topicKey || topicKeys[Math.floor(Math.random() * topicKeys.length)] || 'nano_banana_posters';
  const blueprint = SINGLE_TOPIC_CAROUSEL_BLUEPRINTS[selectedKey] || SINGLE_TOPIC_CAROUSEL_BLUEPRINTS['nano_banana_posters'];

  const slides: CarouselSlideCopy[] = blueprint.slides.map((s: any, idx: number) => ({
    ...s,
    slideIndex: idx + 1,
    cardIndexText: `0${idx + 1} // 08`,
  }));

  const instagramCaption = `${blueprint.captionHook}\n\nHere is the simple step-by-step breakdown:\n\n${slides
    .map((s) => `0${s.slideIndex} // ${s.header}`)
    .join('\n')}\n\n---\n💾 SAVE this post so you have the formulas for your next project.\n✈️ SHARE with a friend or creator who needs this.\n👇 Drop "${blueprint.triggerWord}" in the comments and I will instantly DM you the complete free interactive playbook & prompt templates!\n\nproject\\ciel // BEYOND THE FRAME, INTO FEELING.`;

  const hashtags = [
    '#projectciel',
    '#visualdirecting',
    '#luxurymarketing',
    '#nanobanana',
    '#contentcreator',
    '#creativeagency',
    '#graphicdesign',
    '#marketingtips',
  ];

  return {
    topicKey: selectedKey,
    topicTitle: blueprint.topicTitle,
    triggerWord: blueprint.triggerWord,
    hookHeadline: slides[0]?.header || blueprint.topicTitle,
    slides,
    instagramCaption,
    hashtags,
  };
}

export function extractSlidesFromText(text: string): CarouselSlideCopy[] {
  return generateCarouselCopy({ topicKey: 'nano_banana_posters' }).slides;
}
